describe('Signup Page', () => {
  it('should load english by default', () => {
    cy.visit('/signup')
    cy.url().should('include', '/signup')
  })
  it('should preload the page in english and in french', () => {})
  it('should load the correct default language', () => {})
  it('should have all fields visible', () => {})
  it('should have all of the links are valid', () => {})
  it('should return status 201 when account is created', () => {})
  it('should have the same data in the payload and in formsubmission', () => {})
  it('should log the person in when the account creation is at a 201', () => {})
  it('should send a welcome email when the account is created', () => {})
  it('should be keyboard navigable', () => {})
  it('should accept a valid password of exactly 12 characters that meets all rules', () => {})
  it('should accept a valid password of exactly 32 characters that meets all rules', () => {})
  it('should accept a valid Canadian phone number', () => {})
  it('should submit successfully with each province selected', () => {})
  it('should submit successfully without checking the partner consent checkbox', () => {})
  it('should include consent:true in payload when checkbox is checked', () => {})
  it('should display all error messages in French when language is set to French', () => {})
  it('should link to French versions of Terms of Service and Privacy Policy in French mode', () => {})
  it('should receive and store an auth token after successful 201 response', () => {})
  it('should redirect to the correct post-signup page after account creation', () => {})
})